version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  immich-redirect-proxy-nick:
    container_name: immich-redirect-proxy
    image: python:latest
    ports:
      - "8000:8000/tcp"
    environment:
      TZ: 'America/Chicago'
    restart: unless-stopped
    volumes:
      - ./redirect-multiuser.py:/redirect.py
      - ./install.sh:/install.sh
    entrypoint: '/bin/sh /install.sh'
    networks:
      - python-immich_default

networks:
  python-immich_default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 0.0.0.0/0
        ip_range: 0.0.0.0/0
        gateway: 0.0.0.0
        